### ISSUE TITLE
How to import browser version, or use rendering without `fs` calls, etc.

### ISSUE THREAD

**Issue by mikeerickson** [eta-dev/eta#146]
**Describe the bug**
When using the default import, I receive an error

> ReferenceError: Can't find variable: fs

I am basically trying to use "in memory" rendering, I don't have access to any `fs` type methods, I am just attempting to render from template variables (I don't need to use layouts, etc.)

**To Reproduce**

import * as eta from 'eta'
use code in browser

**Package & Environment Details**
 - Environment: All browsers
 - Version: ex. 1.12.3

**Additional context**
I am building my plugin using rollup

**Comment by nick-allen** [comment]
Any documentation on this? Having similar issue using with typescript trying to import "eta/browser", can't find any documentation on how to import browser compatible version, and not able to polyfill path/fs modules.

**Comment by shadowtime2000** [comment]
@nick-allen The problem arises from the setup of the build system, as the ES version is actually currently set up for node ES and not the actual official ES standard. I'm just going to reopen this.

**Comment by shadowtime2000** [comment]
I once [implemented this before](https://github.com/eta-dev/eta/pull/65) however I ended up reverting it as it would technically be a breaking change by semantic versioning which we follow, as existing code probably imports from the `module` field even though it is built for browser ES modules. @nick-allen @mikeerickson I am thinking of just potentially just having it be another set of files in `dist/browser` which you would have to specifically import, like `import "eta/dist/browser/eta.es.js"`. Thoughts?

**Comment by nick-allen** [comment]
Having a separate import for the browser version would work totally fine for my case, as mentioned in my last comment, I tried something similar using what looked like an earlier effort at supporting something like this via [package.json exports](https://nodejs.org/api/packages.html#subpath-exports), but I get the impression this is either misconfigured, or a typescript issue that didn't fully make it into v4.5, as I couldn't get it to import. Ultimately wound up using [browser import](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#browser) to workaround this, by adding the following to my package.json: 

```
  "browser": {
    "fs": false,
    "path": false
  },
```

This isn't an ideal workaround, despite being easier for me to implement in my environment, instead of trying to have to fuss with webpack polyfill fallbacks in my case.

**Comment by shadowtime2000** [comment]
@nick-allen @mikeerickson This will be added within the next update, which will probably be a patch release, with imports available in `eta/dist/browser/eta.es.min.js` or `eta/dist/browser/eta.es.dev.js`. Let me know if you have any other problems.
