### ISSUE TITLE
import a function from a js file

### ISSUE THREAD

**Issue by AmirABody** [eta-dev/eta#147]
Hi there, Hope you are fine and great!

I was wondering whether it is possible to use import statement in eta or not!
As an example, I can mention: `<% import f1 from './to/path/f1.js' %>`.

I gave it a try in the template engine and faced the following error coming up:
**Cannot use import statement outside a module**

It would be awesome to also use this feature of javascript in the template engine, or even use the *require* of Nodejs.
Thanks!

**Comment by bato3** [comment]
If you must use `import` in eta, then you don't quite understand the MVC design pattern.
In short: you should be delivering processed data that you only display to the template file.

The closest to what you suggest is this example:  https://eta.js.org/docs/syntax/async#example

**Comment by bato3** [comment]
@mikeerickson It comes from: https://github.com/eta-dev/eta/blob/47f8b0f29b9af335e737605e1090834c6621cbca/src/render.ts#L77-L87

And it is related to: https://github.com/eta-dev/eta/blob/47f8b0f29b9af335e737605e1090834c6621cbca/src/polyfills.ts#L7
For what? Why? - I do not know. I am not affiliated with eta. And I'm still learning Node. 


Anyway:

You should create issue and provide more info about your env.

In the meantime, you can create your own async handling through callbacks.

**Comment by shadowtime2000** [comment]
I am going to close this issue as using top-level `import` statements within templates seems unnecessary, inefficient, and frankly a little worrying. @mikeerickson Sorry for the late response, however I will try to look into that issue. Can I ask what browser you are using to test that, since Promise constructors are only non-existent in IE, so I want to see if the method for getting a Promise constructor is faulty.
