### ISSUE TITLE
Make ETA template compatible with ES6 template

### ISSUE THREAD

**Issue by sntran** [eta-dev/eta#176]
**Is your feature request related to a problem? Please describe.**
ES6 templates can be rendered from string similar to ETA using `new Function()` trick`, but Deno Deploy does not like that. Therefore, I'm switching to ETA but trying to avoid modifying the templates themselves.

**Describe the solution you'd like**
- Option to use just `}` as closing delimiter.
- Auto render nested template in interpolation.

**Describe alternatives you've considered**
Right now, I am getting very close to the goal with the following options:

```js
parse: {
  exec: "#",
  interpolate: "",
  raw: "~",
},
tags: ["${", "}}"],
useWith: true,
```

However, I am trying to avoid the double closing curly brackets, but ETA does not like it, i.e. `tags: ["${", "}"]` seems to throw error.

Also, I would also like to avoid the `=` for interpolation. I tried setting `parse.interpolate` to `""` and `parse.exec` to some random string so `${ name }` behaves the same as ES6 template. Yes, I know I would need to use `.map` instead of `.forEach`. However, I can't interpolate raw HTML inside. For example, the following does not work:

```html
${
  name.split("/").map((path, index, array) => {
    return `<a href="${ path }">${ path }</a>`;
  }).join("/");
}
```

**Comment by shadowtime2000** [comment]
@sntran Setting the template delimiters to `["${", "}"]` doesn't seem to be throwing errors for me. Can you share what your error is? Maybe it comes from the fact you have included semicolons in your example, what if you try changing it to this:
```javascript
${
  name.split("/").map(path, index, array) => {
    return `<a href="${ path }">${ path }</a>`
  }).join("/")
}
```

**Comment by sntran** [comment]
@shadowtime2000 Sure, here is the minimal example that will throw the error:

```ts
import { render } from "https://deno.land/x/eta@v1.12.3/mod.ts";

const html = [
    '<h1>',
    '${',
    '   name.split("/").map(p => {',
    '       return `<a href="${p}">${p}</a>`',
    '   }).join("/")',
    '}',
    '</h1>',
].join("\n");

const assigns = {
    name: "Foo/bar",
};

const body = render(html, assigns, {
    async: false,
    parse: {
        exec: "#",
        interpolate: "",
        raw: "~",
    },
    tags: ["${", "}"], // Template delimiters
    varName: "it", // Name of data object in template.
    useWith: true, // scope data as global to avoid `varName`.
});

console.log(body);
```

Further tracing show that if I changed `html` to the following, then it's fine:

```ts
const html = [
    '<h1>',
    '${',
    '   name.split("/").map(p => `<a href="${p}">${p}</a>`).join("/")',
    '}',
    '</h1>',
].join("\n");
```

So the error is throwed with the `})` closing the map function.

Besides, the output is escaped, i.e. `<a href="Foobar">Foobar</a>` is rendered instead of just the "Foobar" link.

And while I tried to create this mininal example, it turned out that Deno Deploy won't run ETA either, due to `new Function` usage, so it's kinda a moot point :D

**Comment by shadowtime2000** [comment]
This is pretty much expected behavior, because if your closing delimiter is a `}` then the parsing engine will start searching for a `}` after a tag is opened to close it, and when it finds it will consider it to be fully closed tag, hence the syntax errors. Just kind of how it is meant to work.

On the topic of `<a href="Foobar">Foobar</a>` being rendered instead of just the link, you can simply add `autoEscape: false` in order to do have the link render, and then for data that's being passed in auto escape it yourself.

Yeah for Deno Deploy, Eta won't work if you are compiling on demand/compiling within the function at all. A work around would be the compile your functions using a script that utilizes `compileToString`, and then writes those templates into javascript files that could be imported by your functions, but it's still a bit messy.

**Comment by sntran** [comment]
Thanks @shadowtime2000! Good to know about the way ETA works.
