### ISSUE TITLE
Question: How to use eta as a templating engine for express?

### ISSUE THREAD

**Issue by nspeedzy** [eta-dev/eta#3]
(This is just a question and not a bug report)

Hello, so i checked the documentation and couldn't find a way to use the eta templating engine for express. So, how to use eta as a templating engine for express? Also, what is the file extension used for the eta templating engine?

**Comment by jimsorock** [comment]
https://eta.js.org/docs/api/file-handling

**Comment by jimsorock** [comment]
@nspeedzy https://eta.js.org/docs/api/file-handling

**Comment by nebrelbug** [comment]
@nspeedzy sorry I wasn't able to get back to you sooner, but @jimsorock's answer is perfect.

For more detailed examples, you can check out https://scotch.io/tutorials/use-ejs-to-template-your-node-application. Since Eta and EJS have such similar APIs, syntax, and functionality, you should only have to tweak a few things in the tutorial.

**Comment by nspeedzy** [comment]
@nebrelbug Thanks! But you guys might want to add a documentation page called "Using ETA with express". Before I close this issue, Isn't `.eta` the extension?

**Comment by nebrelbug** [comment]
Good idea! We’ll work on updating the docs. Excited to see what you create!
