### ISSUE TITLE
using views in data object overwrites template path config

### ISSUE THREAD

**Issue by bbrefeld** [eta-dev/eta#48]
I've been using ETA for a little while now and today suddenly it stopped finding my template files.
After a lot of troubleshooting I noticed my data object was overwriting my default template location.

For example:

I used the following code to set my default location to look for templates
`eta.configure({
  views: path.join(__dirname, "templates")
})`

Now when trying to render a template everything is fine.
This works:
`eta.renderFile("./pages/example", {example: "example"})`

This doesn't:
`eta.renderFile("./pages/example", {views: "example"})`

It will overwrite the config and result in eta being unable to find the templates.

It might be more specific than this but just be aware of this little issue. It might save you a headache debugging

**Comment by shadowtime2000** [comment]
@bbrefeld Is there a reproduction repo I can look at?

**Comment by shadowtime2000** [comment]
@bbrefeld
Hi,
Express's view engine system combines configuration options with the data object which goes in one option. In order to maintain out of the box Express support, if only two parameters are passed to `eta.renderFile` it will assume that the second parameter is a combination of the configuration and data objects. I believe that if you use `eta.renderFile(path, { view: "example" }, {})` it should work.
