### ISSUE TITLE
Complex template not working

### ISSUE THREAD

**Issue by trojanh** [eta-dev/eta#7]
Thanks for this lightweight library. 
Not sure if this is intended to be used this way, but reporting it anyway for future readers as it's not mentioned in the docs. 

Consider the following template
```
const template = `&lt;ApplicantFirstName&gt;{{it.firstName}}&lt;/ApplicantFirstName&gt;`
```

When we use the following, `it.firstName` is replaced by `''`
```
Eta.render(template, { firstName: "ABC" }, { tags: ["{{", "}}"])
```
 output is:
```
`&lt;ApplicantFirstName&gt;&lt;/ApplicantFirstName&gt;`
```

**Package & Environment Details**
 - Environment: Node
 - Version: latest

**Comment by nebrelbug** [comment]
Hey @trojanh, thanks for the report! Actually, your template should look like `{{=it.firstName}}` instead of `{{it.firstName}}`.

The issue stumped me for a while -- I'm so used to the syntax of template engines that use `{{ ... }}` like Squirrelly and Handlebars that I forgot Eta needed the `=` after the opening tag :rofl:!

Thanks for taking the time to create the issue -- let me know if you have any questions :+1:

**Comment by trojanh** [comment]
Thanks @nebrelbug , I think I must have overlooked this.

Any way if you really feel this is so easy to mistake, we must add some highlight for this. I had checked all the docs but I missed this silly thing. 😅

I think you have done great job keeping this library lightweight yet so feature rich and also well documented 🙏

I would love to help you with anything.

**Comment by nebrelbug** [comment]
@trojanh no problem, glad I could help!

Yeah, highlighting would be super helpful. I've also considered making a linting plugin that would loop through the parse results and identify likely errors.

Thanks so much! I've really enjoyed creating Eta.

> I would love to help you with anything.

Thanks! If you want, you could write a tutorial explaining how to use Eta or talking about the benefits of Eta (I'd point users to it from the docs). Otherwise, just using Eta, asking questions, and filing issues is helpful!
